// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BusAnnouncement struct {
	Title       string   `json:"title"`
	Author      string   `json:"author"`
	PublishedAt string   `json:"published_at"`
	Abstract    string   `json:"abstract"`
	Content     []string `json:"content"`
}

type BusInfo struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Price    int       `json:"price"`
	Stations []string  `json:"stations"`
	BusTime  []BusTime `json:"bus_time"`
}

type BusRecord struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	PayTime       string `json:"pay_time"`
	DepartureTime string `json:"departure_time"`
}

type BusTime struct {
	DepartureTime string `json:"departure_time"`
	RemainSeats   int    `json:"remain_seats"`
	OrderedSeats  int    `json:"ordered_seats"`
}

type CardConsumptionRecord struct {
	Address string `json:"address"`
	Money   string `json:"money"`
	Time    string `json:"time"`
}

type ElectricityRechargeRecord struct {
	Money    string `json:"money"`
	Datetime string `json:"datetime"`
}

type ElectricityUsageRecord struct {
	Usage    string `json:"usage"`
	Datetime string `json:"datetime"`
}

type GetBusAnnouncementReq struct {
	Page     int `form:"page,optional" default:"1"`
	PageSize int `form:"page_size,optional" default:"10"`
}

type GetBusAnnouncementResp struct {
	UpdatedAt string            `json:"updated_at"`
	Total     int64             `json:"total"`
	List      []BusAnnouncement `json:"list"`
}

type GetBusInfoReq struct {
	Search string `form:"search,optional"`
}

type GetBusInfoResp struct {
	UpdatedAt string    `json:"updated_at"`
	List      []BusInfo `json:"list"`
}

type GetBusRecordReq struct {
	Uid      string `form:"uid"`
	Page     int    `form:"page,optional" default:"1"`
	PageSize int    `form:"page_size,optional" default:"100"`
}

type GetBusRecordResp struct {
	List []BusRecord `json:"list"`
}

type GetBusReservationReq struct {
	Uid      string `form:"uid"`
	Page     int    `form:"page,optional" default:"1"`
	PageSize int    `form:"page_size,optional" default:"100"`
}

type GetBusReservationResp struct {
	List []BusRecord `json:"list"`
}

type GetCaptchaImageReq struct {
	DeviceID      string `form:"device_id"`
	SecurityToken string `form:"security_token"`
}

type GetCaptchaImageResp struct {
	Img string `json:"img"`
}

type GetCardBalanceReq struct {
	UID      string `form:"uid"`
	DeviceID string `form:"device_id"`
	Token    string `form:"token,optional"`
}

type GetCardBalanceResp struct {
	Balance string `json:"balance"`
}

type GetCardConsumptionRecordsReq struct {
	UID       string `form:"uid"`
	DeviceID  string `form:"device_id"`
	Token     string `form:"token,optional"`
	QueryTime string `form:"query_time"`
}

type GetCardConsumptionRecordsResp struct {
	List []CardConsumptionRecord `json:"list"`
}

type GetElectricityRechargeRecordsReq struct {
	Uid           string `form:"uid"`
	Campus        string `form:"campus,options=zhpf|mgs"`
	Page          string `form:"page"`
	RoomStrConcat string `form:"room_str_concat"`
}

type GetElectricityRechargeRecordsResp struct {
	List []ElectricityRechargeRecord `json:"list"`
}

type GetElectricitySurplusReq struct {
	Uid    string `form:"uid"`
	Campus string `form:"campus,options=zhpf|mgs"`
}

type GetElectricitySurplusResp struct {
	DisplayRoomName string  `json:"display_room_name"`
	RoomStrConcat   string  `json:"room_str_concat"`
	Surplus         float64 `json:"surplus"`
}

type GetElectricityUsageRecordsReq struct {
	Uid           string `form:"uid"`
	Campus        string `form:"campus,options=zhpf|mgs"`
	RoomStrConcat string `form:"room_str_concat"`
}

type GetElectricityUsageRecordsResp struct {
	List []ElectricityUsageRecord `json:"list"`
}

type GetSecurityTokenReq struct {
	DeviceID string `form:"device_id"`
}

type GetSecurityTokenResp struct {
	Level         uint8  `json:"level"`
	SecurityToken string `json:"security_token"`
}

type LoginByCodeReq struct {
	DeviceID string `json:"device_id"`
	PhoneNum string `json:"phone_num"`
	Code     string `json:"code"`
}

type LoginByCodeResp struct {
	UID            string `json:"uid"`
	Token          string `json:"token"`
	BindCardStatus uint8  `json:"bind_card_status"`
}

type LoginBySilentReq struct {
	UID      string `json:"uid"`
	DeviceID string `json:"device_id"`
	PhoneNum string `json:"phone_num,optional"`
	Token    string `json:"token,optional"`
}

type LoginBySilentResp struct {
	Token string `json:"token"`
}

type SendCodeReq struct {
	DeviceID      string `json:"device_id"`
	SecurityToken string `json:"security_token"`
	Captcha       string `json:"captcha,optional"`
	PhoneNum      string `json:"phone_num"`
}

type SendCodeResp struct {
	UserExists bool `json:"user_exists"`
}
